### PR TITLE
update docker sdk to latest version

### PR DESCRIPTION
**Pull request by shizonic**
This resolves the following exception:

```
Traceback (most recent call last):
  File "/home/tm/.local/bin/pwnbox", line 8, in <module>
    sys.exit(main())
  File "/home/tm/.local/lib/python3.9/site-packages/pwnbox/__main__.py", line 131, in main
    pwnbox_container = client.containers.get(config['CONTAINER']['NAME'])
AttributeError: 'function' object has no attribute 'get'
```
Further information can be found at:

- https://github.com/docker/docker-py/issues/1360

### CODE REVIEW

**Comment by DeadPackets** [comment]
I have finals till Sunday, will check right after that and then push a new version with this PR and the other!

Huge thanks for this 👏

**Comment by shizonic** [comment]
> I have finals till Sunday, will check right after that and then push a new version with this PR and the other!
> 
> Huge thanks for this 👏

You are welcome! I want to say thank to YOU! I really appreciate your work and would like to investigate further PRs if welcome...

**Comment by DeadPackets** [comment]
I welcome any additions you would like to add at all to the project! If you have ANY (and I mean any) ideas or recommendations or changes you want to make, just create them as an issue first and I'll let you know if you can go ahead with it!

For `pwnbox-cli`, I don't really have improvements in mind, most of the improvements I can think of are related to `pwnbox` itself. If you can think of anything (for any of my projects!) feel free to drop a PR or an issue.

**Comment by shizonic** [comment]
> I welcome any additions you would like to add at all to the project! If you have ANY (and I mean any) ideas or recommendations or changes you want to make, just create them as an issue first and I'll let you know if you can go ahead with it!
> 
> For `pwnbox-cli`, I don't really have improvements in mind, most of the improvements I can think of are related to `pwnbox` itself. If you can think of anything (for any of my projects!) feel free to drop a PR or an issue.

Thx dude I let you know!

**Comment by shizonic** [comment]
May ask about the progress?

**Comment by DeadPackets** [comment]
Sorry for the delay, checked and merging now!

**Pull request merged**
